# Generated by Django 6.0.5 on 2026-05-29 18:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0002_alter_historicaltipoequipo_id"),
        ("inventario", "0003_alter_historicalunidad_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPrestamo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SOLICITADA", "Solicitada"),
                            ("APROBADA", "Aprobada"),
                            ("PREPARADA", "Preparada"),
                            ("ENTREGADA", "Entregada"),
                            ("DEVOLUCION", "En devolución"),
                            ("CERRADA", "Cerrada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="SOLICITADA",
                        max_length=12,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(blank=True, editable=False)),
                ("fecha_requerida", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_devolucion_comprometida",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.asignatura",
                    ),
                ),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entregado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preparado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical préstamo",
                "verbose_name_plural": "historical préstamos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SOLICITADA", "Solicitada"),
                            ("APROBADA", "Aprobada"),
                            ("PREPARADA", "Preparada"),
                            ("ENTREGADA", "Entregada"),
                            ("DEVOLUCION", "En devolución"),
                            ("CERRADA", "Cerrada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="SOLICITADA",
                        max_length=12,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_requerida", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_devolucion_comprometida",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestamos_aprobados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestamos",
                        to="catalogo.asignatura",
                    ),
                ),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestamos_cerrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entregado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestamos_entregados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preparado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestamos_preparados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestamos_solicitados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "préstamo",
                "verbose_name_plural": "préstamos",
                "ordering": ["-fecha_solicitud", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDetallePrestamo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("cantidad_devuelta", models.PositiveIntegerField(default=0)),
                ("cantidad_no_devuelta", models.PositiveIntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_equipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogo.tipoequipo",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventario.unidad",
                    ),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="prestamos.prestamo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical detalle de préstamo",
                "verbose_name_plural": "historical detalles de préstamo",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DetallePrestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("cantidad_devuelta", models.PositiveIntegerField(default=0)),
                ("cantidad_no_devuelta", models.PositiveIntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "tipo_equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_prestamo",
                        to="catalogo.tipoequipo",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_prestamo",
                        to="inventario.unidad",
                    ),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="prestamos.prestamo",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle de préstamo",
                "verbose_name_plural": "detalles de préstamo",
                "ordering": ["prestamo_id", "id"],
            },
        ),
    ]
