# Generated by Django 5.2.14 on 2026-06-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestamos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleprestamo",
            name="condicion_devolucion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUENO", "Bueno"),
                    ("REPARABLE", "Reparable"),
                    ("MALO", "Malo"),
                ],
                default="BUENO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicaldetalleprestamo",
            name="condicion_devolucion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUENO", "Bueno"),
                    ("REPARABLE", "Reparable"),
                    ("MALO", "Malo"),
                ],
                default="BUENO",
                max_length=10,
            ),
        ),
    ]
