# Generated by Django 5.2.15 on 2026-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prestamos", "0002_detalleprestamo_condicion_devolucion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprestamo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("SOLICITADA", "Solicitada"),
                    ("APROBADA", "Aprobada"),
                    ("PREPARADA", "Preparada"),
                    ("ENTREGADA", "Entregada"),
                    ("DEVOLUCION", "En devolución"),
                    ("CERRADA", "Cerrada"),
                    ("RECHAZADA", "Rechazada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="SOLICITADA",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("SOLICITADA", "Solicitada"),
                    ("APROBADA", "Aprobada"),
                    ("PREPARADA", "Preparada"),
                    ("ENTREGADA", "Entregada"),
                    ("DEVOLUCION", "En devolución"),
                    ("CERRADA", "Cerrada"),
                    ("RECHAZADA", "Rechazada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="SOLICITADA",
                max_length=12,
            ),
        ),
    ]
