# Generated by Django 5.1 / django-simple-history 3.11.0.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalunidad",
            name="codigo_activo",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=40,
                null=True,
            ),
        ),
    ]
