# Generated by Django 5.2.15 on 2026-06-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_historicalunidad_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalunidad",
            name="situacion",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "Disponible"),
                    ("RESERVADA", "Reservada"),
                    ("PRESTADA", "Prestada"),
                    ("REPARACION", "En reparación"),
                    ("BAJA", "De baja"),
                ],
                default="DISPONIBLE",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="unidad",
            name="situacion",
            field=models.CharField(
                choices=[
                    ("DISPONIBLE", "Disponible"),
                    ("RESERVADA", "Reservada"),
                    ("PRESTADA", "Prestada"),
                    ("REPARACION", "En reparación"),
                    ("BAJA", "De baja"),
                ],
                default="DISPONIBLE",
                max_length=12,
            ),
        ),
    ]
