# Generated by Django 5.2.15 on 2026-06-03 17:42

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(max_length=200)),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=120)),
                ("contacto_nombre", models.CharField(blank=True, max_length=160)),
                ("contacto_telefono", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
                "ordering": ["razon_social", "rut"],
            },
        ),
        migrations.AddField(
            model_name="historicalitemordencompra",
            name="codigo_material",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="historicalitemordencompra",
            name="precio_unitario",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="historicalitemordencompra",
            name="unidad_medida",
            field=models.CharField(blank=True, default="UNI", max_length=20),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="codigo_inversion",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="comprador_nombre",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="descuentos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="direccion_despacho",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="fecha_emision",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="fecha_publicacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="numero_inacap",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="recibido_por_nombre",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="referencia_pedido",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="sede_destino",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="historicalordencompra",
            name="tasa_iva",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="itemordencompra",
            name="codigo_material",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="itemordencompra",
            name="precio_unitario",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="itemordencompra",
            name="unidad_medida",
            field=models.CharField(blank=True, default="UNI", max_length=20),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="codigo_inversion",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="comprador_nombre",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="descuentos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="direccion_despacho",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="fecha_emision",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="fecha_publicacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="numero_inacap",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="recibido_por_nombre",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="referencia_pedido",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="sede_destino",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="tasa_iva",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19"), max_digits=5
            ),
        ),
        migrations.CreateModel(
            name="HistoricalProveedor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("razon_social", models.CharField(max_length=200)),
                ("rut", models.CharField(db_index=True, max_length=20)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("ciudad", models.CharField(blank=True, max_length=120)),
                ("contacto_nombre", models.CharField(blank=True, max_length=160)),
                ("contacto_telefono", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical proveedor",
                "verbose_name_plural": "historical proveedores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name="historicalordencompra",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="compras.proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_compra",
                to="compras.proveedor",
            ),
        ),
    ]
